DROP TABLE IF EXISTS user;

CREATE TABLE user (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  firstName TEXT NOT NULL,
  lastName TEXT NOT NULL,
  email TEXT NOT NULL,
  password TEXT NOT NULL,
  salt TEXT NOT NULL
);

DROP TABLE IF EXISTS job;
CREATE TABLE job (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  'type' TEXT NOT NULL,
  area TEXT NOT NULL,
  state TEXT NOT NULL,
  streetAddress TEXT NOT NULL
);

